### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by samis** [tuhdo/os01#1]
I've taken a glance at the PDF in your repository and it looks interesting.  Do you happen to have the source code you used to create it to begin with?

(Note: Storing binary files, particularly large binary files in a Git repository is not a good idea as it increases the overall repository size.  You can solve this by not including the PDF as part of the repository, but as a GitHub release download or a file on a webserver or similar.)

**Comment by tuhdo** [comment]
@samis Sure I will release the book source at some point, after cleaning the junks in it :)

And sure I will store it properly soon.

**Comment by tuhdo** [comment]
@samis I uploaded the book source.

**Comment by tuhdo** [comment]
Done. Now the PDF is put into Release. Thank you for the report.
