### ISSUE TITLE
[pg. 252] [Typo] In os/Makefile.

### ISSUE THREAD

**Issue by compilepeace** [tuhdo/os01#100]
BUILD_DIR=../build/os instead of BUILD_DIR=../build_os
also in os/Makefile,
While converting 'os.c' file into 'os.o', you typed a '-m32' flag which is already mentioned in 'CFLAGS' variable.
:)

**Comment by compilepeace** [comment]
Thank you for writing such an informative book. Indeed gained much from it :)

**Comment by tuhdo** [comment]
@compilepeace I'm glad to hear that :) 

I will fix the issues this weekend.

**Comment by tuhdo** [comment]
Thanks. I fixed it.
