### ISSUE TITLE
[page 82][confusing] .data5 is defined as char, not integer

### ISSUE THREAD

**Issue by gusals3587** [tuhdo/os01#120]
On the third paragraph of page 82, if says

> Finally, the struct of bf2 is the same of bf, except it contains one more data member: .data5, and is defined as an **integer**.

But I thought the reason why bf2 contains those extra 3 bytes was because .data1 was defined as integer, and .data2 ~ data5 didn't fit within those extra 24 bits, so it was allocated new memory

**Comment by gusals3587** [comment]
hmm.. but with this line of logic, I'm guessing the bit_field2 in exercise 4.8.2 should look exactly the same as the one given in the _source_, so I guess the data4 is what's causing those 3 bytes?

**Comment by hkh786ggu** [comment]
`data5` is causing the extra 3 bytes. `data1` to `data4` take up the first 4 bytes so more space has to be made to fit `data5`. 

`data5` is defined as a char in the source so the part about it being an integer is a typo, although it doesn't change the outcome. There's another typo later that says that `data5` can access 8 bits but it can only access 4.

**Comment by tuhdo** [comment]
I fixed it. Thanks.
