### ISSUE TITLE
Question: Page width seems short

### ISSUE THREAD

**Issue by tuxillo** [tuhdo/os01#15]
Hi,

It seems that the page borders for the text is not well adjusted as the text covers just around 60% of the space. I don't find it pretty to my eye so I was wondering if that was on purpose.

In any case, thanks for doing the book! It's been always that I have wanted for quite some time :)

Best regards,
Antonio Huete

**Comment by rjmill** [comment]
I personally prefer having the wide margins for technical/educational books like this. It gives me more space to take notes as I read.

**Comment by tuhdo** [comment]
Yes, it is designed that way. And as @rjmill said, it is for extra material, e.g. comments, footnotes, concepts introduced in the page or taking notes.

I cannot change the layout now as it is deeply involved with the content of the book.
