### ISSUE TITLE
[page 63][content] SIB byte table and example

### ISSUE THREAD

**Issue by Hornobster** [tuhdo/os01#23]
Hi,

On page 63, you use `jmp [eax*2 + ebx]` as a simple example to show how the SIB byte works.
The instruction is assembled to `0x67 ff 24 43`, and `0x43` is the SIB byte, but when I look for 0x43 in the table, it looks like the final address would be `[ebx*2 + eax]`.
It seems to me, from the table, that the SIB byte for `jmp [eax*2 + ebx]` would be `0x58`, which it clearly isn't.

Also, in the next page, there's a small typo:

> After the prefix, comes the opcode 0x67 [...]

It should be `0xff`.

I'm loving your book and I'll continue to contribute!

**Comment by tuhdo** [comment]
Hi,

Thanks for the report. The SIB byte is correct, but the SIB table for referencing is wrong. I will update the table shortly.

**Comment by tuhdo** [comment]
Thanks. I fixed it. I copied the ModR/M table, but forgot to update the values.

And I'm glad to hear that you are enjoying the book! Keep up the good work.
