### ISSUE TITLE
[page 44][content] Transistors aren't capacitors.

### ISSUE THREAD

**Issue by nostrademons** [tuhdo/os01#26]
(2nd to last paragraph in 3.2.2)

Technically, the charge in a DRAM cell is stored in a capacitor, which is a different type of electrical component than a transistor.  I'd suggest something like the following:

"At the physical level, RAM is implemented as a grid of cells that each contain a transistor and an electrical device called a *capacitor*, which stores charge for short periods of time.  The transistor controls access to the capacitor; when switched on, it allows a small charge to be read from or written to the capacitor.  The charge on the capacitor slowly dissipates, requiring the inclusion of a refresh circuit to periodically read values from the cells and write them back after amplification from an external power source."

**Comment by tuhdo** [comment]
It's true. Thank you very much! I forgot the details after a long time reading about it.
