### ISSUE TITLE
Grammatical fix (pg: 9)

### ISSUE THREAD

**Issue by palerdot** [tuhdo/os01#3]
In the page 9 of the pdf, there is a line which says

> e.g. Intel are critical for implementing an operating system or any other software that direct controls the hardware.

which should read

> e.g. Intel are critical for implementing an operating system or any other software **that directly** controls the hardware.

It is better to have the source in this repo, to which people can give pull requests. You should probably want to define some guidelines/format like [page no] [type => grammatical/typo] for you to easily pinpoint the issue and to prevent same issue being raised again.

**Comment by tuhdo** [comment]
Thanks. I will add the source in a few days. But I wonder if people are okay with Lyx, or prefer plain Latex.

**Comment by palerdot** [comment]
You can just start sharing with whatever source you have right now. The audience of a book of this kind will surely find some way to figure out things even if you share the binary of the source :)

**Comment by tuhdo** [comment]
@palerdot I uploaded the source.

**Comment by tuhdo** [comment]
I also fixed the mistake. Thanks for the report.
