### ISSUE TITLE
[pg.62][typo] "... repeated accessed ..."

### ISSUE THREAD

**Issue by PDirks** [tuhdo/os01#39]
typo/grammar issue on p. 62, found in the paragraph in the middle of the page:

> ... if the element is repeated accessed many times...

should be

> ... if the element is _repeatedly_ accessed many times ...

apologies if this was already spotted

**Comment by yuvaldlv** [comment]
oh... thanks...

**Comment by tuhdo** [comment]
Thanks for the report. I fixed it.
