### ISSUE TITLE
[page 71][content] CS and EIP values are swapped

### ISSUE THREAD

**Issue by Hornobster** [tuhdo/os01#41]
Hi,

in page 71, when describing `jmp far [eax]`, you say:

> The far address consumes total of 6 bytes in size for a 16-bit segment and 32-bit address, which is encoded as m16:32 from the table 4.7.1. As can be seen from the figure above, the blue part is a segment address, loaded into cs register with the value 0x1234; the red part is the memory address within that segment, loaded into eip register with the value 0x5678 and start executing from there.

The two values `0x1234` and `0x5678` are switched.

Also, in figure 4.7.1, shouldn't `0x1234` be laid out as `0x34120000`?

In addition to that, could you add a short comment on endianness, explaining why m16:32 is laid out in memory in reverse order?

Thank you.

**Comment by tuhdo** [comment]
The figure is correct (aside from `0x003412` which is supposed to be `0x3412000` as you said) but i forgot to update the text.

Thank you for the report.
