### ISSUE TITLE
[page 96][typo] 0 instead of 1

### ISSUE THREAD

**Issue by Hornobster** [tuhdo/os01#42]
Hi,

At the end of the logical AND explanation, you describe what happens when both operands are not 0:

> 3. If both i and j are not 0, the result is certainly 1, or true.
> (a) Set it accordingly with the instruction at 0x80484a7.
> (b) Then jump over the instruction at 0x80484ae to set the
> variable logical_and at [ebp-0x8] to 0.

The last 0 should be a 1.

**Comment by tuhdo** [comment]
Thanks. I fixed it and also the address where case 3 starts.
