### ISSUE TITLE
k + k = 2^k?

### ISSUE THREAD

**Issue by versine** [tuhdo/os01#45]
In chapter 2, on page 15,  the sentence "a k-input gate uses
k PMOS and k NMOS transistors, a total of 2^k transistors" is bolded. Shouldn't it be 2k instead of 2^k?

**Comment by tuhdo** [comment]
Oh it's true. Thanks for the report. When I see 2 and k, somehow my mind made me think `2^k`.

**Comment by Choco31415** [comment]
This is an issue on page 27 too.

**Comment by tuhdo** [comment]
Thanks. I fixed it.
