### ISSUE TITLE
Assembly Incorrect?

### ISSUE THREAD

**Issue by Choco31415** [tuhdo/os01#46]
On page 25, we have that this C:

```
if (argc1) {
  i=i;
} else {
  i=0;
}
```

And equivalent assembly:

```
cmp DWORD PTR [ebp+0x8],0x0
je 80483f7 <main+0x1c>
mov DWORD PTR [ebp-0x4],0x1
jmp 80483fe <main+0x23>
mov DWORD PTR [ebp-0x4],0x0
```

In the "if" portion of the assembly code (line 3), the registry is set to 0x1. This means i is set to hexadecimal 1, aka 1.

However, in the "if" portion of the C code, i is set to itself. 

Am I missing something by chance?

**Comment by tuhdo** [comment]
It's a typo. It should be `i = 1`. t. Thanks.
