### ISSUE TITLE
[pg.31][grammar] wrong word

### ISSUE THREAD

**Issue by asurafire** [tuhdo/os01#47]
"knowing" in line 1 should be "nothing".

**Comment by tuhdo** [comment]
Probably you are using the old version?  Pg 31 has no such "knowing". Could you specify, which sentence it is? Thanks.

**Comment by asurafire** [comment]
It appears that I have an older version sorry. 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.On 3/1/17, 19:43 Tu Do <notifications@github.com> wrote:

  
    
      Probably you are using the old version? Pg 31 has no such "knowing". Could you specify, which sentence it is? Thanks.
