### ISSUE TITLE
[pg.31] [Typo] "knowing" to "nothing"

### ISSUE THREAD

**Issue by Le0nX** [tuhdo/os01#48]
"if a programmer knows absolutely **knowing** about hardware"

**Comment by tuhdo** [comment]
Which version did you get? The latest version should not have that mistake anymore.

**Comment by tuhdo** [comment]
I see the problem now. The download link is not updated to the latest pdf.

**Comment by tuhdo** [comment]
I've fixed it. Thanks for the report.
