### ISSUE TITLE
[Pg. 80][Question] Assembly Listing

### ISSUE THREAD

**Issue by Choco31415** [tuhdo/os01#55]
On Page 80, there's an assembly listing. I've tried using objdump and gcc to replicate it, but none of my approaches do. How is this assemble listing generated?

**Comment by tuhdo** [comment]
Did you use `-m32` flag? Anyway, the important thing here is the value of each variable, you can ignore the assembly listings. `odjdump` is used for readers to see how the values are laid out in memory.

**Comment by Choco31415** [comment]
Nope. Thank you! I wanted to check my guesses for 4.8.1, 4.8.2. They were correct. :)
