### ISSUE TITLE
[page 207][typo] dd command should have seek=1

### ISSUE THREAD

**Issue by Hornobster** [tuhdo/os01#57]
Hi,

I believe the `dd` command should be invoked with `seek=1` in this case, since we are writing the 2nd sector.

Original:
`   $ dd if=sample of=disk.img bs=512 count=1 seek=0 `

Correction:
`   $ dd if=sample of=disk.img bs=512 count=1 seek=1 `

**Comment by tuhdo** [comment]
Thanks for the report. I will fix it soon.
