### ISSUE TITLE
[page 71][figure layout]: segment and address are reversed

### ISSUE THREAD

**Issue by lykowdk** [tuhdo/os01#6]
The blue box is supposed to contain the segment address 0x1234 and the red box is supposed to contain the address 0x5678. The values do not have the correct colors.

**Comment by tuhdo** [comment]
Ah yes, that's right. I messed up here. The code that I did before was:

```
pushw 0x5678
pushd 0x1234
jmp far [esp]
```

I should have used `esp` to remind the ordering. Thank you for the report.

**Comment by tuhdo** [comment]
Than you. I've just hot fixed the image, so the readers won't get the incorrect version.
