### ISSUE TITLE
Creating your own programming language

### ISSUE THREAD

**Issue by abjrcode** [tuhdo/os01#60]
I have come across this repo by coincidence and I am so happy I found it. I was always fascinated by operating systems and their implementations since college days.

Another thing which always interested me was programming languages. There is a lot of theory and a lot of practical books as well, but there isn't a place where I could find that connects the theory with practical implementation together at the same time and provides a deep understanding to how these concepts relate.

I would love to hear if you know of a such a resource or book ?
Kindest regards,

**Comment by tuhdo** [comment]
I haven't experienced much with compiler books. However, the Compiler course by Alex Aiken (used to be on Coursera) did a really excellent job of providing a foundational theory along with programming assignments to bolster your knowledge.

Probably it is still usable (that is, automatic grader still works) here: http://online.stanford.edu/course/compilers-0

**Comment by MaksOta** [comment]
I came accross this list which you might find usefull
http://aalhour.com/awesome-compilers/#books

**Comment by abjrcode** [comment]
I am gonna close this issue after two useful comments and share my own finding https://github.com/thejameskyle/the-super-tiny-compiler
