### ISSUE TITLE
[pg.9][Repetition Error] Reuses last sentence

### ISSUE THREAD

**Issue by Joshuad2uiuc** [tuhdo/os01#64]
" Most examples revolve around variants of a“Hello World” program. Most examples revolve around variants of a “Hello World” program, which will acquaint you with core concepts. "

**Comment by Joshuad2uiuc** [comment]
Also, this is page 9/313

**Comment by tuhdo** [comment]
Probably you used an old version of the book. It was fixed at some point before this issue. But thanks for the report!
