### ISSUE TITLE
Byte should say Quadword

### ISSUE THREAD

**Issue by greut** [tuhdo/os01#68]
https://github.com/tuhdo/os01/blob/master/book_src/images/04/fundamental_data_types.svg

**Comment by tuhdo** [comment]
Thanks for the report.

**Comment by greut** [comment]
Thanks for the great book!

**Comment by tuhdo** [comment]
@greut Thanks. I'm happy to hear that!

**Comment by gbip** [comment]
I don't know if it you have "regenerated" the book since this issue, but the error is still there !

**Comment by tuhdo** [comment]
Yes. I haven't fixed it. I will do it this weekend. Thanks for the reminder.

**Comment by tuhdo** [comment]
I fixed it. Thanks again for the report.
