### ISSUE TITLE
"Byte sized" vs. "Quadword sized"

### ISSUE THREAD

**Issue by darkstar** [tuhdo/os01#73]
In chapter 4.8.1, "fundamental data types", you show a diagram (figure 4.8.1) which shows the different sized integers. On my PDF it's on page 72.

The quadword-sized [un]signed integers in the diagram are incorrectly labeled as "byte-sized [un]signed integer":
![image](https://user-images.githubusercontent.com/43795/31632547-99530460-b2bd-11e7-9496-07f331a34ee6.png)

**Comment by tuhdo** [comment]
It was fixed a while ago. Could you download the new PDF file?

**Comment by tuhdo** [comment]
Sorry. I updated the image but not yet updated the book. Thanks for the report.

**Comment by tuhdo** [comment]
Thanks I fixed it.
