### ISSUE TITLE
What is the error in this line of code? My program ends unexpectedly

### ISSUE THREAD

**Issue by Clem-Yam** [tuhdo/os01#75]
#include<iostream>
#include<string>

using namespace std;

	struct employee
{
 string empID;
 char *empName;
 float rate, bsal, gsal, netsal;
 float dutyAllow, fuelAllow;
 float tax, socSec;
 int ndayWork;
 	
 float someone();
 string userinfo();
};
	string employee::userinfo()
{
	employee::empName= new char [40];
	cout<< "Enter Your name"<< endl;
	cin>>employee::empName;
	cout<<"Enter Your ID Number"<< endl;
	cin>>employee::empID;
	A:
	cout<< "Enter Your Number of Days Of work"<< endl;
	cin>>employee::ndayWork;
	
	if (employee::ndayWork>31)
	{
	   goto A;
	}
	
}
 
 float employee::someone()
 {
 	char choice;
	cout<<"****WELCOME TO KOFORIDUA NURSES PORTAL*****"<< endl;
	cout<< "Please enter Your denomination= ";
	cout<<"Nurse = 1"<< endl<< "Doctor=2"<< endl;
	cin>> choice;
	
	switch (choice)
	{
		case 1:
			if(choice<=1)
			{
			
			 cout<<"Daily Mark is 8Ghc"<<endl;
			 
			 
			 employee::netsal=8* employee::ndayWork;
			 cout<<"Your name is "<<employee::empName<<endl;
			 cout<<"Your ID is "<<employee::empID<<endl;
			 cout<<"Your monthly salary is "<< employee::netsal<< endl;
			}
			break;
		case 2:
			if(choice==2)
			{
				
			cout<<"Daily Mark is 10Ghc"<<endl;
			 employee::netsal=10* employee::ndayWork;
			 cout<<"Your name is "<<employee::empName<<endl;
			 cout<<"Your ID is "<<employee::empID<<endl;
			 cout<<"Your monthly salary is "<< employee::netsal<< endl;
			
			}
			break;
		default:
			cout<<"Error"<< endl;
			
		
	}
 }

int main()
{
	
	int salary;
	
	
	employee Doctor, Nurse;
	Nurse.someone();
	Nurse.userinfo();
	
   	
	
		
	system("PAUSE");
	return 0;
}

**Comment by tuhdo** [comment]
Well sorry I think it is better be answered on Stackoverflow.
