### ISSUE TITLE
Run OS on physical hardware?

### ISSUE THREAD

**Issue by kvu787** [tuhdo/os01#78]
I've skimmed over the book PDF, and it looks like you are running the OS on a QEMU virtual machine. Does the book provide instructions on how to run this on a physical machine, such as the Intel Galileo board?

**Comment by tuhdo** [comment]
Yes, it is possible. If you use a floppy disk, then the disk image as described in the book works as is. Of course, you would not want to use a floppy disk, but rather a USB device. The point of using a floppy disk is that it is easy to understand and build a simple bootloader. If you want to load your kernel on a USB device, you can use [syslinux](http://www.syslinux.org/wiki/index.php?title=The_Syslinux_Project) and let it load your kernel. I already built one and loaded on a real laptop. I intend to add a syslinux tutorial into the book when I have time.

I'm not sure about Intel Galileo board, as it may differ from the regular PC, e.g. no BIOS/UEFI, so you must adapt it to your board. However, the book does provide short tutorial on how to build a binary image by a linker script and how to build for GDB debugging (only available if you run QEMU, or you must implement your own GDB server in your code). It is common to build and debug on a QEMU machine, then test on a real machine.

**Comment by kvu787** [comment]
Thanks for the response Tu.

A couple of related questions:

* Any reason you chose syslinux instead of GRUB? I've read that [syslinux is simpler](https://www.reddit.com/r/archlinux/comments/2l5rvk/syslinux_or_grub/).
* What is the easiest way to get a from-scratch bootloader+kernel like yours to run on a physical machine and communicate with the outside world? Like, what peripherals would you try programming first? I'm trying to bare metal code on an ARM device to talk to my Windows 10 desktop over UART.

Let me know if I should continue this thread on a different place (instead of this GitHub issue).

**Comment by tuhdo** [comment]
> Any reason you chose syslinux instead of GRUB? I've read that syslinux is simpler.

Yes, `syslinux` is simpler to setup, even though the documentation is lacking. It is also easier to build a module that loads your kernel. I also have more experience with `syslinux`.

> What is the easiest way to get a from-scratch bootloader+kernel like yours to run on a physical machine and communicate with the outside world? Like, what peripherals would you try programming first? I'm trying to bare metal code on an ARM device to talk to my Windows 10 desktop over UART.

Always check the processor manuals. In your case, you should check the manuals of your specific ARM processor to learn the boot procedure and implement accordingly. For example, if I remember correctly, when power on/reset, ARM issues an interrupt to jump to the address written in `0x0`; in the case of x86, for BIOS boot, the CPU always executes code at `0x7c00` after loading the first 512 bytes (1st sector) from a bootable disk. Then, you start write all the code from there. UEFI is more involved, as you usually use a framework, e.g. [edk2](https://github.com/tianocore/edk2) to bootstrap a standard environment.

To communicate with the outside world, you can use an UART. However, on PC, with BIOS, you can use interrupt service `10h` or writing directly to the memory address starting at `0xB8000` - the video memory). You can also use LEDs to get some output. It depends on the mechanism supported on your platform. 


> Let me know if I should continue this thread on a different place (instead of this GitHub issue).

It's ok to post here.

**Comment by kvu787** [comment]
The boot process for ARM does not seem very standardized, since it's different between the Raspberry Pi and Beaglebone Black boards.

For bare metal code, what defines the interface between the software and a USB device? Do I need to write a separate USB driver based on the peripheral hardware (RPI vs. BBB), or based on the ISA (ARMv7 vs. ARMv8)?

For example, I'm trying to connect an ARM device to a guest VM using a USB-to-UART cable. It works when I run Ubuntu 12.04 / Linux 3.2.0 / 64-bit, but not when I run Ubuntu 16.04 / Linux 4.4.0 / 64-bit. I wonder where is a good place to start debugging this...

Thanks,

Kevin

**Comment by tuhdo** [comment]
Sorry for the late response.

> The boot process for ARM does not seem very standardized, since it's different between the Raspberry Pi and Beaglebone Black boards.

Boot process for ARM processors should be similar. It's just that the boards wrap the boot process and provide their own boot abstraction. You might need to read the manuals for booting processes of a specific board.



> For bare metal code, what defines the interface between the software and a USB device? Do I need to write a separate USB driver based on the peripheral hardware (RPI vs. BBB), or based on the ISA (ARMv7 vs. ARMv8)?

Yes, you need to write a USB driver to enable communication with USB devices from your board by following the specification: http://www.usb.org/developers/docs/

However, I think the development boards provide simpler interfaces to interact with the USB. You should check your board manuals. I'm not sure about this because I haven't used RPI or BBB.

> For example, I'm trying to connect an ARM device to a guest VM using a USB-to-UART cable. It works when I run Ubuntu 12.04 / Linux 3.2.0 / 64-bit, but not when I run Ubuntu 16.04 / Linux 4.4.0 / 64-bit. I wonder where is a good place to start debugging this...

You should check if the device works in the host OS. If it is, then it might be a problem with your VM. If you work on Linux, the communication should be available for a USB device or UART.

**Comment by kvu787** [comment]
No problem. Thanks for answering my questions, and for writing this book. What's the best way to reach you if I have more questions?

I got the USB-to-UART cable working with a plain ubuntu/precise32 image on VirtualBox, which uses Linux 3.13.0-32-generic. It doesn't work with the ubuntu/precise32 Vagrant box, which uses kernel 3.2.0-126-virtual. So I guess the way the Linux kernel is packaged for Vagrant messed with the UART driver somehow.

**Comment by tuhdo** [comment]
> No problem. Thanks for answering my questions, and for writing this book. What's the best way to reach you if I have more questions?

You can contact my Github email: tuhdo1710@gmail.com
