### ISSUE TITLE
[pg.62][grammar] Missing word

### ISSUE THREAD

**Issue by garciaadrian** [tuhdo/os01#95]
> The mod field divides addressing modes into 4 different categories. Further
combines with the r/m field, exactly one addressing mode can be selected
from one of the 24 rows. If an instruction only requires one operand, then
the column can be ignored. **Then the reg/opcode field finally provides
the if an instruction requires one**.

Maybe opcode extension was supposed to go in there?

**Comment by tuhdo** [comment]
Thanks I will fix it soon.

**Comment by tuhdo** [comment]
I clarified it in the book. Thanks for reporting.
