### ISSUE TITLE
follow along

### ISSUE THREAD

**Issue by dabaf** [tuhdo/os01#96]
Hi, 
I just started reading your book. I am on subject about "objdump". I am trying to follow along; the command you propose suppose that one has a certain file ex: objdump -d hello. where do I find the file hello?

thank for the reply,

**Comment by dabaf** [comment]
Thank you for your response. I understand that it is a file, but where do I find that file to follow along with the practice. The is no file in GitHub as far as I looked around.

Thanks again,

Sent from my iPhone

On Jun 30, 2018, at 1:26 AM, Tu Do <notifications@github.com<mailto:notifications@github.com>> wrote:


It's just the name of the compiled file from the code listing. You can choose whatever name you want. On Linux, extensions are optional. The hello file is equivalent to hello.exe on Windows.

**Comment by tuhdo** [comment]
Right. This is a bit confusing. The `hello` file is just a hypothetical compiled file I used as an example for `objdump` command line usage. I should explicitly mention that fact, or put a sample listing.

Thanks. I will fix it.

**Comment by tuhdo** [comment]
I fixed it. Thanks.
