### ISSUE TITLE
[pg. 65][content]Example 4.5.6

### ISSUE THREAD

**Issue by zhanglx13** [tuhdo/os01#99]
In the example, instruction jmp [eax*4+0x1234] generates the machine code 67 ff 24 8d 34 12 00 00. The ModR/W (24) code indicates that there is a SIB field, which is 8d. From the SIB table, 8d indicates [ecx * 4] (not [eax * 4]).
I tried on my machine and the SIB code is 85 instead of 8d. This explains the [eax * 4] part.
Also, the ModR/W code does not indicate a following displacement. How does CPU expect the ending 34 12 00 00 to be a displacement?

**Comment by zhanglx13** [comment]
I figured it out. Table 4.5.3 should have [*] as the 7th column in the first row instead of EBP. And the footnote of the table explains why a disp32 follows eax*4.

**Comment by tuhdo** [comment]
Thanks for reporting. I will fix it this weekend.

**Comment by tuhdo** [comment]
I added more explanation to the SIB byte for the example 4.5.6. The SIB byte in the example should be 85, not 8d. Thanks. By default, if not register is used, it is default to the 6th column (not 7th), which is the EBP register.
